namespace api.Dto.User.Notification
{
  public enum NotificationType
  {
    SocialMessage = 0,
    FriendRequest = 1,
    GameRequest = 2,
    System = 3 //AutoGenerated result, request responses
  }
}