trigger:
  branches:
    include:
      - main

pool:
  name: DefaultWorld

variables:
  # serviceConnection: ${serviceConnection}  # <-- update
  # webAppName: ${webAppName}               # <-- update
  buildConfiguration: 'Release'
  projectPath: 'api/api.csproj'
  clientPath: '.' # Angular project is in the repo root
  # distSubFolder: 'world-xi' # value in angular.json "outputPath"

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
    - script: |
        dotnet restore $(projectPath)
        dotnet publish $(projectPath) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish
      displayName: Restore & Publish

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    
    - script: |
        npm ci
        npm run build -- --configuration production
      displayName: Build Angular
      workingDirectory: '$(Build.SourcesDirectory)'


    - powershell: |
        $srcRoot = "$(Build.SourcesDirectory)"
        $publish = "$(Build.ArtifactStagingDirectory)\publish\wwwroot"

        $dist = Join-Path $srcRoot "dist\world-xi"
        $browser = Join-Path $dist "browser"

        Write-Host "Looking for Angular build output:"
        Write-Host "  $browser"
        Write-Host "  $dist"

        if (Test-Path $browser) { $final = $browser }
        elseif (Test-Path $dist) { $final = $dist }
        else {
          Write-Host "DEBUG: dist folder tree:"
          if (Test-Path (Join-Path $srcRoot "dist")) {
            Get-ChildItem -Recurse -Force (Join-Path $srcRoot "dist") |
              Select-Object FullName,Length,LastWriteTime | Format-Table -AutoSize
          } else {
            Write-Host "No dist folder found at $(Join-Path $srcRoot 'dist')"
          }
          throw "Angular build output not found at dist/world-xi[/browser]."
        }

        Write-Host "Copying from: $final"
        Write-Host "Copying to:   $publish"
        New-Item -ItemType Directory -Force -Path $publish | Out-Null
        robocopy $final $publish /E /NFL /NDL /NJH /NJS /NP
        if ($LASTEXITCODE -gt 7) { exit $LASTEXITCODE } else { exit 0 }
      displayName: Copy Angular dist to wwwroot


    # Zip & publish artifact
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(serviceConnection)'
              appName: '$(webAppName)'
              appType: webApp
              package: '$(Pipeline.Workspace)/drop/drop.zip'
