namespace api.Models
{
    public enum NotificationType
    {
        SocialMessage = 1,
        FriendRequest = 2,
        GameRequest = 3,
        System = 4 //AutoGenerated result, request responses
    }
}